send:
  name: Send command
  description: Sends a command to a BenQ projector.
  fields:
    device_id:
      name: Node
      description: The Node you want to send a command to
      required: true
      selector:
        device:
          integration: espmeshmesh
    command:
      name: Command
      description: A command to send.
      required: true
      example: "menu"
      selector:
        text:
    action:
      name: Action
      description: The action for the given command.
      required: false
      example: "on"
      default: "?"
      selector:
        text:
send_raw:
  name: Send Raw command
  description: Sends a raw command to a espMeshMesh Node.
  fields:
    device_id:
      name: Node
      description: The Node you want to send a command to
      required: true
      selector:
        device:
          integration: espmeshmesh
    command:
      name: Command
      description: A raw command to send.
      required: true
      example: "*menu=on#"
      selector:
        text:
